# Site settings
baseurl = "https://dayvillefire.org/"
languageCode = "en-us"
title = "Dayville Fire Company"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-93897024-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Dayville Fire Company"
  description = "Combination fire company proudly serving the Dayville, CT area for 80 years."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  headerImage = "https://dayvillefire.org/img/header-bg.jpg"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  [params.social]
    github		= "dayvillefire"
    facebook		= "DayvilleFireCompany"
    facebook_admin	= "17807199"  # This needs to be a page admin to get domain insights
    twitter		= "DayvilleFire"
    twitter_domain	= "dayvillefire.org" # This domain shows in twitter cards as "View on `twitter_domain`"
    #googleplus		= "NozzleIo"
    #pinterest		= "nozzleio"
    instagram		= "dayvillefire"
    #youtube		= "nozzleio"
    linkedin		= "dayville-fire-company"

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Dayville Fire Company"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "Services"
    portfolio = "Resources"
    about = "About"
    upcoming = "Upcoming"
    team = "Our Team"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # postpended links
    [[menu.postpend]]
      url = "/training-center/"
      name = "Training Center"
      weight = 10

    [[menu.postpend]]
      url = "http://photos.jbuchbinder.com/Fire-Photography/Dayville-Fire-Company/"
      name = "Photos"
      weight = 20 

    [[menu.postpend]]
      url = "https://members.dayvillefire.org/"
      name = "Members"
      weight = 30

  # Hero section
  [params.hero]
    title = "Dayville Fire Company"
    subtitle = "Home of the angry beaver"
    buttonText = "Join Us"
    buttonLink = "/application/"

  # Services section
  [params.services]
    enable = true
    title = "Services"
    subtitle = ""

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-heartbeat"
      title = "Medical Services"
      description = ""
      url = "#"

    [[params.services.row.list]]
      icon = "fa-thermometer-full"
      title = "Training Center"
      description = "State-of-the-art firefighter training center."
      url = "/training-center/"

    [[params.services.row.list]]
      icon = "fa-fire-extinguisher"
      title = "Fire Prevention"
      description = ""
      url = "#"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-fire"
      title = "Fire Response"
      description = ""
      url = "#"

    [[params.services.row.list]]
      icon = "fa-dollar"
      title = "Charitable Fundraising"
      description = ""
      url = "#"

    [[params.services.row.list]]
      icon = "fa-graduation-cap"
      title = "Education"
      description = ""
      url = "#"

  # Portfolio section
  [params.portfolio]
    enable = false
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfolio"
    subtitle = ""

  [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"

  #[params.upcoming]
  #  enable = true
  #  title = "Upcoming Events"
  #  subtitle = ""

    #[[params.upcoming.events]]
    #  img = "/pdf/Fire-Officer-II.jpg"
    #  title = "Fire Officer II (Aug-Sep 2017)"
    #  link = "/pdf/Fire-Officer-II.pdf"

  # About section
  [params.about]
    enable = true
    title = "About"
    subtitle = "The **Dayville Fire Company** is a combination fire company that protects the village of Dayville from medical, fire, hazardous material, and environmental emergencies. The Dayville Fire Company was established in 1937 to protect the ever-growing village of Dayville, but the roots of fire protection in Dayville can be traced back to the mid to late 1800s when the fire protection for the local mills would also respond to fires in the village.<br/><br/>The Dayville Fire Company covers an area that is about nine square miles in size and is one of the most diverse and busy fire districts -- not only in the Town of Killingly but also in all of Windham County. Dayville is the center of the [Town of Killingly](http://www.killingly.org/) and covers the main intersection of Route 12 and Route 101, which is the location of many commercial buildings and shopping plazas. We also cover the town's industrial park, housing several large warehouses, distribution centers, and manufacturing facilities; some of these include the town's largest employer: the fifth largest [Frito Lay](http://www.fritolay.com/) plant in North America, and a three-turbine natural gas power plant. We also protect [Quinebaug Valley Community College](http://qvcc.edu/), the [Killingly elementary and middle schools](http://www.killinglyschools.org), an alternative high school, and several other preschools and daycare facilities. We also cover about six miles of Interstate 395, have multiple large elderly housing complexes, and a large residential base."
    endpoint = "[Be part<br>of our<br>story!](/application/)"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "prym.jpg"
      date = "1937"
      title = "Incorporated"
      description = "Dayville Fire Company was incorporated from the Prym Mill Fire Brigade."

    [[params.about.events]]
      img = "station.jpg"
      date = "1977"
      title = "New Station"
      description = ""

    [[params.about.events]]
      img = "training-center.jpg"
      date = "2015"
      title = "Training Center Opens"
      description = "The Lt. Dennis R Lemery Memorial Training Center opens, offering fire training services for the fire companies in Killingly and the surrounding areas."

  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    center = true
    title = "Meet Dayville's Firefighters"
    #subtitle = ""
    #description = ""

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "Chief-Kevin-Ide.jpg"
      name = "Kevin Ide"
      position = "Chief"
      reportsTo = ""
      scope = [
        "Fire Officer III",
        "Fire Service Instructor II"
      ]
      # For bio markdown and even multiline strings are available.
      bio = ""
      #social = [
      #  ["fa-twitter", "#"],
      #  ["fa-facebook", "#"],
      #  ["fa-linkedin", "#"]
      #]

    [[params.team.members]]
      img = "Chief-Todd-Wakefield.jpg"
      name = "Todd Wakefield"
      position = "Deputy Chief"
      bio = ""
      #social = [
      #  ["fa-twitter", "#"],
      #  ["fa-facebook", "#"],
      #  ["fa-linkedin", "#"]
      #]
      scope = [
        "Fire Officer I",
        "Fire Service Instructor I"
      ]

    [[params.team.members]]
      img = "Chief-Eric-Lemery.jpg"
      name = "Eric Lemery"
      position = "Assistant Chief"
      scope = [
        "Dayville Fire District President",
	"Fire Service Instructor I"
      ]
      bio = ""
      #social = [
      #  ["fa-twitter", "#"],
      #  ["fa-facebook", "#"],
      #  ["fa-linkedin", "#"]
      #]

    [[params.team.members]]
      img = "Chief-Mike-Shabenas.jpg"
      name = "Mike Shabenas"
      position = "Assistant Chief"
      scope = [
        "Fire Service Instructor I"
      ]

    [[params.team.members]]
      img = "Captain-Gahrett-Bond.jpg"
      name = "Gahrett \"Bubba\" Bond"
      position = "Fire Captain"
      scope = [
        "Fire Service Instructor I"
      ]

    [[params.team.members]]
      img = "Lt-Scott-Shatney.jpg"
      name = "Scott Shatney"
      position = "Fire Captain"
      scope = [
        "Fire Officer I",
        "Fire Service Instructor I"
      ]

    [[params.team.members]]
      img = "Captain-Wayne-Morin.jpg"
      name = "Wayne Morin"
      position = "Fire Captain"
      scope = [
        "Fire Officer I",
        "Fire Service Instructor I"
      ]

    [[params.team.members]]
      img = "Lt-Duane-Anderson.jpg"
      name = "Duane Anderson"
      position = "EMS Captain"
      scope = [
        "Emergency Medical Services Instructor"
      ]

    [[params.team.members]]
      img = "Captain-Mike-Breyer.jpg"
      name = "Mike Breyer"
      position = "Captain, Fire Police"

    [[params.team.members]]
      img = "Lt-Holly-Anderson.jpg"
      name = "Holly Anderson"
      position = "Fire Lieutenant"
      scope = [
        "Emergency Medical Technician"
      ]

    [[params.team.members]]
      img = "Lt-Jessica-Leader.jpg"
      name = "Jessica Leader"
      position = "Fire Lieutenant"
      scope = [
        "Fire Service Instructor I"
      ]

    [[params.team.members]]
      img = "Lt-Henry-Frechette.jpg"
      name = "Henry Frechette"
      position = "Lieutenant, Fire Police"

    [[params.team.members]]
      img = "Engineer-James-Beaudoin.jpg"
      name = "James Beaudoin"
      position = "Engineer"

    [[params.team.members]]
      img = "Engineer-Craig-Bond.jpg"
      name = "Craig Bond"
      position = "Engineer"

    [[params.team.members]]
      img = "Engineer-John-Carvalho.jpg"
      name = "John Carvalho"
      position = "Engineer"

    [[params.team.members]]
      img = "Engineer-Gary-Cote.jpg"
      name = "Gary Cote"
      position = "Engineer"

  # Client section
    [params.clients_list]
      enable = true
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      title = "Proud to support"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "pierce.png"
        link = "http://www.piercemfg.com/"
        title = "Pierce Manufacturing"

      [[params.clients]]
        logo = "kochek.png"
        link = "https://www.kochek.com/"
        title = "Kochek"

      [[params.clients]]
        logo = "tft.png"
        link = "http://www.tft.com/"
        title = "Task Force Tips"

      [[params.clients]]
        logo = "kb.png"
        link = "https://kbambulance.com/"
        title = "KB Ambulance Corps"

      [[params.clients]]
        logo = "afts.png"
        link = "http://www.americanfiretrainingsystems.com/"
        title = "American Fire Training Systems"

      [[params.clients]]
        logo = "shipman.png"
        link = "http://www.shipmans.com/"
        title = "Shipman's"

      [[params.clients]]
        logo = "firematic.png"
        link = "http://firematic.com/"
        title = "Firematic"

      [[params.clients]]
        logo = "cs.png"
        link = "http://csspecialty.com/"
        title = "CS Specialty"

  # Contact section
  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = "This contact form is *not* intended for emergency services requests. If you are experiencing or have witnessed a fire or medical incident that you wish to report, *call 9-1-1 immediately*."
    buttonText = "Send message"

    infoLeft = """**CONTACT**

_Chief Kevin Ide_<br/>
Dayville Fire Company<br/>
465 Hartford Pike<br/>
P.O. Box 307<br/>
Dayville, CT 06241

    """
    infoRight = """
Emergency: 911<br/>
Office: 860-774-5525
    """

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "k.ide@dayvillefire.org"

    # Success and error message overwrite for async contact form
    thanks = "Thank you for contacting us."
    error = "We're sorry, but your message could not be sent; please contact us at k.ide@dayvillefire.org instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.topic]
      text = "Topic *"
      warning = "Please select a topic."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/dayvillefire"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/DayvilleFireCompany/"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "https://www.linkedin.com/company/dayville-fire-company/"

    [[params.footer.social]]
      icon = "fa-instagram"
      link = "http://www.instagram.com/dayvillefire/"

    [[params.footer.social]]
      icon = "fa-camera"
      link = "http://photos.jbuchbinder.com/Fire-Photography/Dayville-Fire-Company/"

    [[params.footer.social]]
      icon = "fa-yelp"
      link = "https://www.yelp.com/biz/dayville-fire-company-dayville"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "/privacy-policy/"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "/terms-of-use/"

